site_name: BMEVIAUAC09 Szoftverfejlesztés laboratórium 1
site_author: Albert István, Tóth Tibor
copyright: Copyright &copy; BME-VIK-AUT
repo_name: bmeviauac01/laborok
repo_url: https://github.com/bmeviauac01/laborok

theme:
  name: material
  custom_dir: overrides
  language: hu
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: aut
      primary: aut
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
    - content.action.edit
  logo: logo-bme-aut.png
  favicon: favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - md_in_html
  - pymdownx.keys

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: Europe/Budapest
      locale: hu
  - git-committers:
      repository: bmeviauac01/laborok
      branch: master

nav:
  - "Szoftverfejlesztés laboratórium 1":
      - index.md
      - GitHub.md
      - GitHub-Actions.md
      - VisualStudio.md
      - GitHub-credentials.md
  - "Laborok":
      - "Reporting Services": Lab-ReportingServices/index.md
      - "Lekérdezés optimalizálás": Lab-QueryOptimization/index.md
      - "MSSQL": Lab-MSSQL/index.md
      - "MongoDB": Lab-MongoDB/index.md
      - "Entity Framework & REST": Lab-EFREST/index.md
