site_name: BMEVIAUAC09 Szoftverfejlesztés laboratórium 1
site_author: Dudás Ákos
copyright: Copyright &copy; BME VIK AUT
repo_name: bmeviauac01/laborok
repo_url: https://github.com/bmeviauac01/laborok

theme:
  name: material
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Váltás sötét témára
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Váltás világos témára
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
  logo: images/logo-bme-aut.png
  favicon: images/favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - "Szoftverfejlesztés laboratórium 1":
      - index.md
      - GitHub.md
      - GitHub-Actions.md
      - VisualStudio.md
      - GitHub-credentials.md
  - "Laborok":
      - "Reporting Services": Lab-ReportingServices/index.md
      - "Lekérdezés optimalizálás": Lab-QueryOptimization/index.md
      - "MSSQL": Lab-MSSQL/index.md
      - "MongoDB": Lab-MongoDB/index.md
      - "Entity Framework & REST": Lab-EFREST/index.md
